language: java

branches:
  only:
  - master

script:
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then git config user.name "Travis CI"; git config user.email "$COMMIT_AUTHOR_EMAIL"; mvn release:prepare -B; mvn release:perform -B Darguments="-Dmaven.deploy.skip=true";
  else mvn clean verify; fi